---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    vars:
      test1_pwd: abc
      test2_pwd: def
    tasks:

    - name: "just execute a ls -lrt command"
      shell: "cat /home/madhuboyina/work/git/ansible/group_vars/bb_config/bbexporter_config.yml"
      register: "output"

    - debug: var=output.stdout_lines

    - name: search and replace
      replace:
        path: /home/madhuboyina/work/git/ansible/group_vars/bb_config/bbexporter_config.yml
        regexp: 'test1_pwd'
        replace: {{test1_pwd}}
